name: CraftifyPlugin
version: 1.0.0
main: org.foranly.craftifyplugin.CraftifyPlugin
api-version: '1.21'
description: Receives players' Spotify state (Craftify mod) and displays it.
authors:
  - foranly
commands:
  nowplaying:
    description: Shows the player's current Spotify state.
    usage: /nowplaying
    permission: craftifyplugin.nowplaying
  craftifyplugin:
    description: Reloads the CraftifyPlugin configuration.
    usage: /craftifyplugin reload
    permission: craftifyplugin.reload
permissions:
  craftifyplugin.nowplaying:
    description: Allows viewing your own Spotify state.
    default: true
  craftifyplugin.reload:
    description: Allows reloading the CraftifyPlugin configuration.
    default: op
